return {
    {
    abbreviation = "STB",
    groupId = "15258900",
    color = Color3.fromRGB(0, 0, 255),
},
    {
    abbreviation = "HCG",
    groupId = "35824344",
    color = Color3.fromRGB(255, 255, 255),
},
    {
    abbreviation = "SG",
    groupId = "33405101",
    color = Color3.fromRGB(152, 152, 152),
},
    {
    abbreviation = "YGG",
    groupId = "32522100",
    color = Color3.fromRGB(255, 0, 255),
},
    {
    abbreviation = "SSW",
    groupId = "32366170",
    color = Color3.fromRGB(0, 170, 0),
},
    {
    abbreviation = "SFM",
    groupId = "14692389",
    color = Color3.fromRGB(255, 0, 0),
},
    {
    abbreviation = "HS",
    groupId = "35043967",
    color = Color3.fromRGB(0, 255, 255),
},
    {
    abbreviation = "FBA",
    groupId = "34227955",
    color = Color3.fromRGB(248, 248, 248),
},
    {
    abbreviation = "556",
    groupId = "676128643",
    color = Color3.fromRGB(255, 0, 4),
},
    {
    abbreviation = "RD",
    groupId = "35700202",
    color = Color3.fromRGB(196, 40, 28),
},
    {
    abbreviation = "GGE",
    groupId = "5625000",
    color = Color3.fromRGB(138, 171, 133),
},
    {
    abbreviation = "LTF",
    groupId = "35928564",
    color = Color3.fromRGB(200, 200, 200),
},
    {
    abbreviation = "CTB",
    groupId = "35432142",
    color = Color3.fromRGB(255, 0, 255),
},
    {
    abbreviation = "SINISTER",
    groupId = "35177141",
    color = Color3.fromRGB(255, 255, 255),
},
    {
    abbreviation = "YCP",
    groupId = "34764219",
    color = Color3.fromRGB(255, 255, 0),
},
    {
    abbreviation = "TVS",
    groupId = "35987274",
    color = Color3.fromRGB(85, 170, 255),
},
    {
    abbreviation = "SON",
    groupId = "13288070",
    color = Color3.fromRGB(255, 0, 255),
},
    {
    abbreviation = "TNT",
    groupId = "33859257",
    color = Color3.fromRGB(85, 255, 0),
},
}
