return {
    {
        abbreviation = "YGG",
        groupId = 32522100,
        color = Color3.fromRGB(170, 0, 255),
    },
    {
        abbreviation = "SG",
        groupId = 33405101,
        color = Color3.fromRGB(152, 152, 152),
    },
    {
        abbreviation = "HS",
        groupId = 35043967,
        color = Color3.fromRGB(0, 255, 255),
    },
    {
        abbreviation = "HCG",
        groupId = 35824344,
        color = Color3.fromRGB(255, 119, 0),
    },
    {
        abbreviation = "SFM",
        groupId = 14692389,
        color = Color3.fromRGB(196, 40, 28),
    },
    {
        abbreviation = "FBA",
        groupId = 34227955,
        color = Color3.fromRGB(248, 248, 248),
    },
    {
        abbreviation = "STB",
        groupId = 15258900,
        color = Color3.fromRGB(0, 0, 255),
    },
    {
        abbreviation = "SON",
        groupId = 13288070,
        color = Color3.fromRGB(255, 0, 255),
    },
    {
        abbreviation = "TVS",
        groupId = 35987274,
        color = Color3.fromRGB(85, 170, 255),
    },
    {
        abbreviation = "TNT",
        groupId = 33859257,
        color = Color3.fromRGB(0, 255, 0),
    },
    {
        abbreviation = "OTB",
        groupId = 865134394,
        color = Color3.fromRGB(255, 119, 0),
    },
    {
        abbreviation = "Logic",
        groupId = 35700202,
        color = Color3.fromRGB(196, 40, 28),
    },
    {
        abbreviation = "GGE",
        groupId = 5625000,
        color = Color3.fromRGB(138, 171, 133),
    },
    {
        abbreviation = "LAC",
        groupId = 6288849,
        color = Color3.fromRGB(248, 248, 248),
    },
    {
        abbreviation = "MKZ",
        groupId = 35928564,
        color = Color3.fromRGB(200, 0, 0),
    },
    {
        abbreviation = "SINISTER",
        groupId = 35177141,
        color = Color3.fromRGB(255, 255, 255),
    },
    {
        abbreviation = "YCP",
        groupId = 34764219,
        color = Color3.fromRGB(255, 255, 0),
    },
}
